puts "Question: What does the following error message tell you?"
puts " "
puts "  SyntaxError: (irb):2: syntax error, unexpected ')', expecting '}'"
puts "    from /usr/local/rvm/rubies/ruby-2.0.0-rc2/bin/irb:16:in `<main>'"
puts " "
puts "Answer: It tells me I typed a parentheses instead of a curly bracket"
